[build]
# Install backend dependencies
command = "pip install -r requirements.txt"

[deploy]
# Build frontend, then copy to backend
command = "cd frontend && npm install && npm run build && cd .. && cp -r frontend/dist backend/app/static"

[start]
# Start the unified FastAPI+frontend service
command = "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
